language: python
python:
  - 2.7
sudo: false

env:
    - TEST_DIR="tests"

# Setup anaconda
before_install:
  - pip install --upgrade pip;
  - pip install -r dev-requirements.txt


# Run test
script:
  - nosetests $TEST_DIR

notifications:
  slack: simpeg:1KZq5giMtlJJ58TijIPgqf7n

