language: python
python:
  - 2.7
  - 3.6

sudo: false

env:
  - TEST_DIR="tests"

install:
  - pip install --upgrade pip;
  - pip install -r dev-requirements.txt


# Run test
script:
  - nosetests $TEST_DIR -v -s

notifications:
  slack: simpeg:1KZq5giMtlJJ58TijIPgqf7n

