language: python
python:
  - 2.7
sudo: false

env:
    - TEST_DIR="tests"

# Setup anaconda
before_install:
  - pip install --upgrade pip;
  - pip install -r dev-requirements.txt
  - pip install git+git://github.com/simpeg/simpeg.git@dev
  - python setup.py install
  # - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh -O miniconda.sh; fi
  # - chmod +x miniconda.sh
  # - ./miniconda.sh -b
  # - export PATH=/home/travis/anaconda/bin:/home/travis/miniconda/bin:$PATH
  # - conda update --yes conda


# Run test
script:
  - nosetests $TEST_DIR

notifications:
  slack: simpeg:1KZq5giMtlJJ58TijIPgqf7n

